### PR TITLE
fix(http.js): fix fetch-h2 response collision

### LINKED ISSUE #249: http response handling changes of epsagon 1.56.1 still produce runtime errors
even with the recent fixes of #244, we're still seeing errors with epsagon enabled, that are otherwise not a problem:

```
RangeError: Resource length mismatch (possibly incomplete body)
    at throwLengthMismatch (./node_modules/fetch-h2/dist/lib/body.js:17:11)
    at StreamResponse.validateIntegrity (./node_modules/fetch-h2/dist/lib/body.js:167:13)
    at awaitBuffer.then.already_1.tap.buffer 
```

could be caused by epsagon, consuming the chunks of the response.

### PR DESCRIPTION
**Pull request by ranrib**
1. Removing unused Wreck instrumentation (it wasn't used regardless of this PR).
2. Adding instrumentation to flag fetch-h2 library.
3. Adding instrumentation to `clientRequest.on('response')` -> `response.on('data')` to capture data in a non interfering way.
4. The shimmer upgrade is exactly to a fix we need to support instrumentation of async funcs inside classes (this is the only change in the lib - https://github.com/othiym23/shimmer/commit/ec15ba2bf2cffc25622fca0d277ea68f0ae2d8ee)

fixes https://github.com/epsagon/epsagon-node/issues/249

### CODE REVIEW

File: src/events/http.js [hunk 1]
```diff
@@ -215,6 +216,69 @@ function httpWrapper(wrappedFunction) {
...
+                return function internalResponseOnWrapper(resEvent, resCallback) {
+                    if (resEvent !== 'data' || typeof resCallback !== 'function') {
+                        return wrappedResFunction.apply(this, [resEvent, resCallback]);
+                    }
+                    const resPatchedCallback = (chunk) => {
+                        if (chunk) {
+                            const totalSize = chunks.reduce(
+                                (total, item) => item.length + total,
+                                0
+                            );
```
Comment (galbash) [inline src/events/http.js]: don't make the calculation each time, keep a sum

File: src/events/http.js [hunk 2]
```diff
@@ -215,6 +216,69 @@ function httpWrapper(wrappedFunction) {
                 this, buildParams(url, options, patchedCallback)
             );
 
+            /**
+             * Wraps 'on' method in a response to capture data event.
+             * @param {Function} wrappedResFunction The wrapped end function
+             * @returns {Function} The wrapped function
+             */
+            function responseOnWrapper(wrappedResFunction) { // eslint-disable-line no-inner-declarations,max-len
```
Comment (galbash) [inline src/events/http.js]: must it be defined inside `httpWrapper`? it is getting very messy. better get `chunks` as a parameter (by adding another wrapping level) - not a must just my personal opinion, let me know if you think otherwise

Comment (galbash) [reply src/events/http.js]: same with the next one

File: src/events/http.js [hunk 3]
```diff
@@ -215,6 +216,69 @@ function httpWrapper(wrappedFunction) {
...
+            }
+
+            /**
+             * Wraps 'on' method in a request to capture response event.
+             * @param {Function} wrappedReqFunction The wrapped end function
+             * @returns {Function} The wrapped function
+             */
+            function requestOnWrapper(wrappedReqFunction) { // eslint-disable-line no-inner-declarations,max-len
+                // epsagonMarker is sent only on our call in this module
+                return function internalRequestOnWrapper(reqEvent, reqCallback, epsagonMarker) {
```
Comment (galbash) [inline src/events/http.js]: might be better to set epsagonMarker to something more unique then 'true'

File: src/events/http.js (hunk 2 above)
Comment (galbash) [reply src/events/http.js]: these eslint disables share my opinion I guess

File: src/events/http.js [hunk 4]
```diff
@@ -215,6 +216,69 @@ function httpWrapper(wrappedFunction) {
...
+                        epsagonMarker ||
+                        typeof reqCallback !== 'function'
+                    ) {
+                        return wrappedReqFunction.apply(this, [reqEvent, reqCallback]);
+                    }
+                    const reqPatchedCallback = (res) => {
+                        if (res.EPSAGON_PATCH) {
+                            return reqCallback(res);
+                        }
+                        res.EPSAGON_PATCH = true;
```
Comment (galbash) [inline src/events/http.js]: i'd check res is not undefined just to be on the safe side

File: src/events/http.js [hunk 5]
```diff
@@ -307,21 +369,25 @@ function httpWrapper(wrappedFunction) {
...
-                        }
-                    });
+                    // Listening to data only if options.epsagonSkipResponseData!=true or no options
+                    if (!options || (options && !options.epsagonSkipResponseData)) {
+                        res.on('data', (chunk) => {
+                            if (chunk) {
+                                const totalSize = chunks.reduce(
+                                    (total, item) => item.length + total,
+                                    0
+                                );
```
Comment (galbash) [inline src/events/http.js]: same

File: src/events/http.js [hunk 6]
```diff
@@ -307,21 +369,25 @@ function httpWrapper(wrappedFunction) {
...
-                            return;
-                        }
-                        const totalSize = chunks.reduce((total, item) => item.length + total, 0);
-                        if (totalSize + chunk.length <= MAX_HTTP_VALUE_SIZE) {
-                            chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk);
-                        }
-                    });
+                    // Listening to data only if options.epsagonSkipResponseData!=true or no options
+                    if (!options || (options && !options.epsagonSkipResponseData)) {
+                        res.on('data', (chunk) => {
```
Comment (galbash) [inline src/events/http.js]: this looks like shared logic that can be extracted

**Review by galbash — CHANGES_REQUESTED** [review]
some small comments

File: src/events/http.js (hunk 1 above)
Comment (ranrib) [reply src/events/http.js]: 👍

File: src/events/http.js (hunk 2 above)
Comment (ranrib) [reply src/events/http.js]: 👍

File: src/events/http.js (hunk 3 above)
Comment (ranrib) [reply src/events/http.js]: 👍

File: src/events/http.js (hunk 4 above)
Comment (ranrib) [reply src/events/http.js]: 👍

File: src/events/http.js (hunk 5 above)
Comment (ranrib) [reply src/events/http.js]: 👍

File: src/events/http.js (hunk 6 above)
Comment (ranrib) [reply src/events/http.js]: 👍

**Review by galbash — APPROVED** [review]
