### PR TITLE
fix(http.js): multiple params not supported

### LINKED ISSUE #165: http.get(url, options) not supported
The `get` function of the NodeJS `http` module can be called with `options` or with `url, [options]. The wrapper was built only for the `options` case, and assumes that the first argument is always an object, when it can be an object, a string, or a `URL` object.

When `http.get` is used with a URL as in https://github.com/adobe/helix-resolve-git-ref/blob/233400fb22d69c79153d7ff126d8ca85c0210ce2/src/index.js#L44 it results in traces to HTTP requests being recorded as pointing to `http://localhost/`. This is due to the assumption that `options` will always be an object here: https://github.com/epsagon/epsagon-node/blob/b9ab8dd8043087a34abe2bcd0c69a669ea6fe51b/src/events/http.js#L90-L95

### PR DESCRIPTION
**Pull request by henperez**
Fixed #165

### CODE REVIEW

File: src/events/http.js [hunk 1]
```diff
@@ -73,51 +74,114 @@ function resolveHttpPromise(httpEvent, resolveFunction, startTime) {
...
 }
 
+/**
+ * Builds the HTTP Params array
+ * @param {string} input The URL, if exists
+ * @param {object} options The Options object, if exists
+ * @param {callback} callback The callback function, if exists
+ * @returns {object} The params array
+ */
+function buildParams(input, options, callback) {
```
Comment (galbash) [inline src/events/http.js]: maybe use ...args or arg1, arg2, arg3

File: src/events/http.js [hunk 2]
```diff
@@ -73,51 +74,114 @@ function resolveHttpPromise(httpEvent, resolveFunction, startTime) {
...
+            options = a;
+            input = undefined;
+        }
+
+        if ((typeof options === 'function') && (!callback)) {
+            callback = options;
+            options = null;
+        }
+
         if (callback && callback.__epsagonCallback) { // eslint-disable-line no-underscore-dangle
```
Comment (galbash) [inline src/events/http.js:120]: move this to before the args parsing

File: src/events/http.js [hunk 3]
```diff
@@ -73,51 +74,114 @@ function resolveHttpPromise(httpEvent, resolveFunction, startTime) {
...
+
 /**
  * Wraps the http's module request function with tracing
  * @param {Function} wrappedFunction The http's request module
  * @returns {Function} The wrapped function
  */
 function httpWrapper(wrappedFunction) {
-    return function internalHttpWrapper(options, callback) {
+    return function internalHttpWrapper(a, b, c) {
+        let input = a;
```
Comment (galbash) [inline src/events/http.js]: call it url (like the API?)

File: src/events/http.js [hunk 4]
```diff
@@ -73,51 +74,114 @@ function resolveHttpPromise(httpEvent, resolveFunction, startTime) {
...
+}
+
 /**
  * Wraps the http's module request function with tracing
  * @param {Function} wrappedFunction The http's request module
  * @returns {Function} The wrapped function
  */
 function httpWrapper(wrappedFunction) {
-    return function internalHttpWrapper(options, callback) {
+    return function internalHttpWrapper(a, b, c) {
```
Comment (galbash) [inline src/events/http.js]: instead of a, b, c you can use `...args` I think

File: src/events/http.js [hunk 5]
```diff
@@ -73,51 +74,114 @@ function resolveHttpPromise(httpEvent, resolveFunction, startTime) {
...
+        let input = a;
+        let options = b;
+        let callback = c;
+        if (!(['string', 'URL'].includes(typeof input)) && !callback) {
```
Comment (galbash) [inline src/events/http.js]: document (here is `request(options, [callback])`)

File: src/events/http.js [hunk 6]
```diff
@@ -73,51 +74,114 @@ function resolveHttpPromise(httpEvent, resolveFunction, startTime) {
...
+            callback = b;
+            options = a;
+            input = undefined;
+        }
+
+        if ((typeof options === 'function') && (!callback)) {
```
Comment (galbash) [inline src/events/http.js:115]: doc this case as well

File: src/events/http.js [hunk 7]
```diff
@@ -73,51 +74,114 @@ function resolveHttpPromise(httpEvent, resolveFunction, startTime) {
...
+
+            if (typeof parsedUrl === 'string') {
+                parsedUrl = urlLib.parse(parsedUrl);
+            }
+
             const hostname = (
-                options.hostname ||
-                options.host ||
-                (options.uri && options.uri.hostname) ||
+                (parsedUrl && parsedUrl.hostname) ||
```
Comment (galbash) [inline src/events/http.js:134]: did you check this? should work It just seems like maybe it won't

**Review by galbash — CHANGES_REQUESTED** [review]
looks good, few comments

**Review by galbash — APPROVED** [review]
