### PR TITLE
openwhisk: various fixes

### LINKED ISSUE #221: openwhisk:  invoking sub-actions causes process to hang on errors
if an openhwisk action invokes another actions, and that action responds with an error, the process seems to hang.

### LINKED ISSUE #223: openwhisk: actions invoked with 'result:true' don't show result in traces
if an openwhisk action is invoked with `result:true`, the API directly returns the result of the action and not the entire response object. in this case, the trace doesn't contain information about the return value.

### LINKED ISSUE #224: openwhisk: params of action invocations not recorded in traces
it would be practical to see the params of action invocations in the traces. currently they are not added to the metadata map.

### PR DESCRIPTION
**Pull request by tripodsan**
- fixes #221

The problem was, that the tracer that receives the `responsePromise` would never continue, because the `responsePromise` would never resolve or reject in case of an error by the `request` promise.

- fixes #223 

actions invoked with `result:true` were not returning the entire response, so the response was not properly recorded.

- fixes #224 

also added the params of the actions to be invoked

### CODE REVIEW

File: src/events/openwhisk.js [hunk 1]
```diff
@@ -31,24 +31,52 @@ function openWhiskWrapper(wrappedFunction) {
...
                         activation_id: res.activationId,
-                        response: res.response,
+                        response: resp,
                     }
                 );
                 invokeEvent.setDuration(utils.createDurationTimestamp(startTime));
                 resolve();
+            }).catch((err) => {
+                eventInterface.setException(invokeEvent, err);
+                reject(err);
```
Comment (galbash) [inline src/events/openwhisk.js]: let's resolve here (we are deferring it anyway, and this promise should generally be resolved when the request is done). We can actually use finally here and put the resolve there (instead of in the then and catch clauses). What do you think?

File: src/events/openwhisk.js [hunk 2]
```diff
@@ -31,24 +31,52 @@ function openWhiskWrapper(wrappedFunction) {
         ]);
 
         invokeEvent.setResource(resource);
+        eventInterface.addToMetadata(invokeEvent, {
+            params: options.params,
```
Comment (galbash) [inline src/events/openwhisk.js:35]: maybe let's pass this as the third argument? (so it won't be recorded when metadataOnly=True)

File: src/events/openwhisk.js [hunk 3]
```diff
@@ -31,24 +31,52 @@ function openWhiskWrapper(wrappedFunction) {
...
+                let resp = res.response;
+                if (resp && resp.result && resp.result.body && resp.result.body.length > 100) {
+                    // create copy so we can trim the long response body
+                    resp = Object.assign({}, resp);
+                    resp.result = Object.assign({}, resp.result);
+                    resp.result.body = `${resp.result.body.substring(0, 100)}...(truncated)`;
+                }
                 eventInterface.addToMetadata(
                     invokeEvent,
                     {
```
Comment (galbash) [inline src/events/openwhisk.js:71]: let's move this to metadataOnly=false as well (use the third argument instead of the second)

**Review by galbash — COMMENTED** [review]
looks good, @ranrib can you have a look at the comments to fit it to our conventions and merge it?

File: src/events/openwhisk.js (hunk 2 above)
Comment (tripodsan) [reply src/events/openwhisk.js:35]: but then it is not consistent with the data that is added in the runner. there all the params are added to the default map:
https://github.com/epsagon/epsagon-node/blob/abcf003c2ab88170e018f9aba650d537d1cb6332/src/wrappers/openwhisk.js#L73-L79

File: src/events/openwhisk.js (hunk 1 above)
Comment (tripodsan) [reply src/events/openwhisk.js]: ok.

File: src/events/openwhisk.js (hunk 3 above)
Comment (tripodsan) [reply src/events/openwhisk.js:71]: ok, I exclude the body and the headers from the default map....

**Review by ranrib — APPROVED** [review]
