### PR TITLE
fix(http.js): fix non function in got http

### LINKED ISSUE #295: Doesn't work with `got`
epsagon version: 1.61.5
got version: 11.0.2

Recently added [got](https://github.com/sindresorhus/got) to my project and received the following error when calling `got.get(url, options)` with Epsagon enabled

```
TypeError: i is not a function
      at ClientRequest.patchedCallback (webpack:///../node_modules/epsagon/dist/bundle.js?:1:63790)
      at Object.onceWrapper (events.js:428:26)
      at ClientRequest.emit (events.js:333:22)
      at ClientRequest.EventEmitter.emit (domain.js:485:12)
      at ClientRequest.origin.emit (webpack:///../node_modules/got/node_modules/@szmarczak/http-timer/dist/source/index.js?:39:20)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:602:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
      at TLSSocket.socketOnData (_http_client.js:471:22)
      at TLSSocket.emit (events.js:321:20)
      at TLSSocket.EventEmitter.emit (domain.js:485:12)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:273:9)
      at TLSSocket.Readable.push (_stream_readable.js:214:10)
      at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```

The error is thrown by the following line https://github.com/epsagon/epsagon-node/blob/master/src/events/http.js#L273 because callback is an object and not a function.
image

### PR DESCRIPTION
**Pull request by ranrib**
fixes: https://github.com/epsagon/epsagon-node/issues/295

### CODE REVIEW

File: src/events/http.js [hunk 1]
```diff
@@ -268,8 +268,7 @@ function httpWrapper(wrappedFunction) {
                 }
 
                 updateAPIGateway(res.headers, httpEvent);
-
-                if (callback) {
+                if (callback && typeof callback === 'function') {
```
Comment (haimrait) [inline src/events/http.js:271]: callback === 'function' is enough because typeof undefined/null !== 'function'

**Review by haimrait — APPROVED** [review]
